version: "3"

services:

  backend:
    image: 192.168.136.12:5000/devops-cicd-demo/backend:${IMAGE_TAG:-latest}
    ports:
      - "8000:8000"
    environment:
      ENVIRONMENT: production

  frontend:
    image: 192.168.136.12:5000/devops-cicd-demo/frontend:${IMAGE_TAG:-latest}
    ports:
      - "80:80"

  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: strongpassword