version: "3"

services:

  backend:
    image: ghcr.io/ilya3503/devops-cicd-demo/backend:latest
    ports:
      - "8000:8000"
    environment:
      ENVIRONMENT: test

  frontend:
    image: ghcr.io/ilya3503/devops-cicd-demo/frontend:latest
    ports:
      - "80:80"

  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: example