name: CI-CD

on:
  push:
    branches: [ main ]

jobs:

  build-and-push:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    outputs:
      image-backend: ghcr.io/${{ github.repository }}/backend:latest
      image-frontend: ghcr.io/${{ github.repository }}/frontend:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set lowercase repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build backend image
        run: |
          docker build -t ghcr.io/$REPO/backend:latest ./backend

      - name: Build frontend image
        run: |
          docker build -t ghcr.io/$REPO/frontend:latest ./frontend

      - name: Push backend image
        run: docker push ghcr.io/$REPO/backend:latest

      - name: Push frontend image
        run: docker push ghcr.io/$REPO/frontend:latest

  deploy-prod:
    runs-on: self-hosted
    needs: build-and-push
    environment:
      name: prod
      url: http://192.168.136.11
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to prod server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 192.168.136.11
          username: iadmin
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/devops-demo
            git pull origin main
            docker pull ghcr.io/ilya3503/devops-cicd-demo/backend:latest
            docker pull ghcr.io/ilya3503/devops-cicd-demo/frontend:latest
            docker compose -f deploy/docker-compose.prod.yml up -d